"""initial_schema

Revision ID: d0636d6975a9
Revises: 
Create Date: 2026-05-11 11:04:31.578274
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd0636d6975a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
